config/routes.rb
SecretSanta::Application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :users do
    resources :exchanges do
      member do
        post 'create_match'
      end
    end
  end

  post 'create_exchange' => 'home#create_exchange'
  post 'update_exchange' => 'home#update_exchange'
  post 'create_match' => 'matches#create_match'

  

end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
  has_many :user_exchange
  has_many :users, through: :user_exchange

  has_many :matches
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  # include Devise::Controllers::InternalHelpers

  # skip_filter :authenticate_inviter!
  # skip_filter :authenticate!

  #the form to create a new exchange
  def new

  end

  #the POST request to process and create a new exchange
  def create
    @exchange = Exchange.new(exchange_params)
    @user = User.find(params[:user_id])
    if @exchange.save && @user.exchanges << @exchange
      flash[:notice] = "Your exchange was created successfully."
    else
      flash[:notice] = "There was a problem creating your to do exchange."
    end
  redirect_to user_exchanges_path
  end

  # the page to edit a exchange's account information
  def edit
    @exchange = Exchange.find(params[:id])
  end

  # The PUT request to update exchange information
  def update
    @exchange = Exchange.find(params[:id])
    if @exchange.update_attributes(exchange_params)
      flash[:notice] = "Your exchange was updated successfully."
    else
      flash[:notice] = "There was a problem updating your exchange."
    end
    redirect_to 'exchange#edit'
  end

  def create_match
    @exchange = Exchange.find(params[:id])
    if Match.match_users!(@exchange)
      flash[:notice] = "Users matched successfully. Gift away!"
    else
      flash[:alert] = "There was a problem matching the users in your exchange. Please try again."
    end
    redirect_to user_exchange_path(user_id: current_user.id)
  end


  #the method to delete a exchange
  def destroy
    @exchange = Exchange.find(params[:id])
    if @exchange.destroy
      flash[:notice] = "Exchange was destroyed."
    else
      flash[:notice] = "There was a problem destroying the exchange."
    end
    redirect_to 'exchange#index'
  end

  #show an individual exchange
  def show
    users = User.find(params[:user_id])
    @exchange = Exchange.find(params[:id])
    if !@exchange
      redirect_to user_exchanges_path
    end
  end

  #show all the exchanges
  def index
    @user = User.find(params[:user_id])
    if @user
      @exchanges = @user.exchanges
    else
      redirect_to root_path
    end
  end


  private

  def exchange_params
    params.require(:exchange).permit(:exchange_name, :due_date, :price)
  end
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/views/exchanges/index.haml
%h3 Welcome 
%h1 
  =current_user.email
%h1 Your Exchanges

-@exchanges.each do |exchange|
  %h3=link_to exchange.exchange_name, user_exchange_path(current_user, exchange)

app/views/exchanges/show.haml
=current_user.email
=current_user.first_name
%h3 Exchange Name
%h1
  =@exchange.exchange_name
%br
%h3 Exchange Participants
-exchange_users = @exchange.users
-exchange_users.each do |user|
  =user.first_name
  =user.last_name
  %br 
  =user.email
  %br
%br
%h3 Exchange Matches
-@exchange.matches.each do |match|
  %b
    =match.gifter.first_name
    =match.gifter.last_name
  %br
  is giving
  %b
    =match.giftee.first_name
    =match.giftee.last_name
  %br 
  a present!
  %br
  %br

%h3 Randomly match everyone together!
= form_tag(create_match_user_exchange_path :method => 'post', :multipart => true) do
  = submit_tag "Go!", class: "btn btn-large", id: "submit-home"